

spring:
  profiles:
    active: dev

ocr:
  url: https://7we3mnhgt6.apigw.ntruss.com/custom/v1/24984/3632f985fd8c43f9e5604956709cd1e0a3bbb4e808524e2619b72b4bc9cfac0f/general
  key: aGd0SkZZTkhCWEl1elVndlhlbElrWU9iZ3VTUXJFb1g=


  naver client id = pWs764j6llstp4AaZJnN
  naver client secret = xV0NPPKkhJ
  redirect-uri = http://localhost:3000/naver/callback/
  session-state: oauth_state
  profile-api-url: https://openapi.naver.com/v1/nid/me

  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URL}
    session-state: oauth_state
  profile-api-url: https://openapi.naver.com/v1/nid/me

  kakao:
    client_id: ${KAKAO_RESTAPI_KEY} 2be62d284a437f3474515610528b82e5
    redirect_uri: ${KAKAO_REDIRECT_URL} http://localhost:8080/kakao/callback/
    profile-api-url: https://kapi.kakao.com/v2/user/me
    client_secret: ${KAKAO_CLIENT_SECRET} Cr6GbxjdI1ubnwUiB77jmA5gUnskKMIA???
